default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: o1e_development

test:
  <<: *default
  database: o1e_test

production:
  <<: *default
  database: o1e_production
  username: o1e
  password: <%= ENV['O1E_DATABASE_PASSWORD'] %>
